# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='vCare', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_live', models.BooleanField(default=True, help_text='Show Live Clinic Status badge')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinic settings',
            },
        ),
    ]
